src/main/java/input/ChunkColumn.java, src/main/java/operations/ChunkingOperation.java, src/main/java/operations/chunking/ChunkCondition.java, src/main/java/operations/chunking/DayCondition.java, src/main/java/operations/chunking/MonthCondition.java, src/main/java/operations/chunking/PatientCondition.java, src/main/java/operations/chunking/YearCondition.java, src/main/java/parsers/ChunkValue.java, src/main/java/table/RecordComparator.java, src/test/java/operations/ChunkingOperationTest.java
To look at the individual steps, please look at branch
chunking_with_table. 
I have merged master into my branch several times but incorrectly. This is why I have created this branch with only the new files so we can easily merge it into master.
=> Basic chunking 

src/test/java/operations/FilterOperationTest.java
Extra test case that covers the missing field-not-found case
=> Extra testcase to cover missing use-case

doc/Deliverable 4/Class diagram.uxf, doc/Deliverable 4/Operations diagram.uxf, doc/Deliverable 4/Parser diagram.uxf, doc/Deliverable 4/Table diagram.uxf
UML diagrams of our program. Can be opened with UMLet. UMLet can be downloaded from http://www.umlet.com/changes.htm
=> UML diagrams

src/main/java/operations/LSAOperation.java, src/test/java/operations/LSAOperationTest.java
Lag Sequential Analysis Operation.
See https://blackboard.tudelft.nl/bbcswebdav/pid-2443413-dt-content-rid-8386462_2/courses/34575-141504/Health%20Informatics%20project%20-%20SDA-%202015.pdf
page 19
=> Lsa operation

src/main/java/operations/ChunkingOperation.java, src/main/java/operations/CodingOperation.java, src/main/java/operations/ConnectionOperation.java, src/main/java/operations/FilterOperation.java, src/main/java/operations/coding/MultipleOccurrencePattern.java, src/main/java/operations/coding/NullPattern.java, src/main/java/operations/coding/Pattern.java, src/main/java/operations/coding/SingleOccurrencePattern.java, src/test/java/operations/ChunkingOperationTest.java, src/test/java/operations/CodingOperationTest.java, src/test/java/operations/ConnectionOperationTest.java, src/test/java/operations/coding/SingleOccurrencePatternTest.java
findPattern works with index instead of iterator. Also some bug fixes and additional tests.
=> Coding extension

src/main/java/operations/ConnectionOperation.java, src/main/java/operations/FilterOperation.java, src/test/java/operations/ConnectionOperationTest.java, src/test/java/operations/FilterOperationTest.java
Tests modified to use the new constructor
=> Removed unused constructors

src/main/java/input/Parser.java, src/main/java/input/Settings.java, src/main/java/operations/ChunkingOperation.java, src/main/java/operations/CodingOperation.java, src/main/java/operations/ConnectionOperation.java, src/main/java/operations/FilterOperation.java, src/main/java/table/Table.java, src/main/resources/correct_xml.xml, src/test/java/input/XMLReaderTest.java, src/test/java/operations/ChunkingOperationTest.java, src/test/java/operations/CodingOperationTest.java, src/test/java/operations/ConnectionOperationTest.java, src/test/resources/settings.xml, src/test/resources/test1.xml, src/test/resources/test2.xml
Tables now have names. The name has to be specified in the settings file.
=> Table naming

src/main/java/table/Chunk.java, src/main/java/table/Table.java, src/test/java/table/ChunkTest.java, src/test/java/table/TableTest.java
Added tests for Table and Chunk.
=> Table_testing

src/main/java/operations/LSAOperation.java, src/main/java/operations/lsa/DayGrouper.java, src/main/java/operations/lsa/Grouper.java, src/main/java/operations/lsa/SingleGrouper.java, src/test/java/operations/LSAOperationTest.java
Improved LSA to support lag based on day, by giving the extra argument new DayGrouper().
=> Lsa improvements

src/main/java/input/Settings.java, src/main/java/table/value/Column.java, src/main/resources/duplicate_names.xml, src/main/resources/empty_format.xml, src/main/resources/empty_name.xml, src/main/resources/no_delimiter.xml, src/main/resources/no_format.xml, src/main/resources/no_format_time.xml, src/main/resources/no_name.xml, src/main/resources/no_settings.xml, src/main/resources/no_startline.xml, src/main/resources/no_table_name.xml, src/main/resources/no_target_time.xml, src/main/resources/wrong_startline.xml, src/main/resources/wrong_target_time.xml, src/main/resources/wrong_type.xml, src/main/resources/wrong_xml_config.xml, src/test/java/input/XMLReaderTest.java, src/test/java/table/value/ColumnTest.java, src/test/resources/test1.xml, src/test/resources/test2.xml
Changed column type check: wrong type throws an exception. Also changed the tests and some xml files.
=> Column_fix

src/main/java/main/Main.java, src/main/java/operations/FilterOperation.java, src/main/java/operations/LSAOperation.java, src/main/java/table/Table.java
Fixed all 2 PMD and all 2 findbugs errors.
Also some code was formatted different, hence the long commits.
=> Pmd findbugs

src/main/java/operations/BetweenOperation.java, src/test/java/operations/BetweenOperationTest.java
Makes it possible to give different date columns for both type of recordevents in a BetweenOperation.
=> Between two dates

src/main/java/input/Parser.java, src/main/java/operations/patterns/MultipleOccurrencePattern.java, src/main/java/operations/patterns/SingleOccurrencePattern.java, src/main/java/operations/patterns/condition/RecordOccurrenceCondition.java, src/main/java/table/Record.java, src/test/java/operations/CodingOperationTest.java, src/test/java/operations/patterns/SingleOccurrencePatternTest.java, src/test/java/operations/patterns/condition/RecordOccurrenceConditionTest.java
Record now has a table name in it.
=> Record with table name

src/main/java/table/StateTransistionMatrix.java, src/main/java/table/StateTransitionMatrix.java, src/main/java/table/value/NumberValue.java, src/test/java/table/StateTransitionMatrixTest.java
Creation of a state transition matrix. You will have to give the table and which column contains the states. This implementation does count when the transition between two states are the same states.
Also added a simple method for adding a number to NumberValue.class
=> State Transition Matrix

src/main/java/table/Record.java
Adapted Record to extend a LinkedHashMap, so all keys are automatically sorted.
=> LinkedHashMap for Record

.gitignore, src/main/java/export/Exporter.java, src/main/java/input/CsvReader.java, src/main/java/input/XmlReader.java, src/main/java/operations/patterns/MultipleConditionPattern.java, src/main/java/operations/patterns/PatternFactory.java, src/main/java/operations/patterns/PatternMatcher.java, src/main/java/table/Chunk.java, src/main/java/table/Record.java, src/main/java/table/Table.java, src/main/java/table/value/DateConversion.java, src/test/java/export/ExporterTest.java, src/test/java/input/XmlReaderTest.java, src/test/java/operations/CodingOperationTest.java, src/test/java/operations/patterns/CountTest.java, src/test/java/operations/patterns/PatternFactoryTest.java, src/test/java/operations/patterns/PatternMatcherTest.java, src/test/java/table/TableFileTest.java, src/test/java/table/value/DateConversionTest.java
Look at commit messages for details.
=> Coverage fixes

src/main/java/main/GUI.java, src/main/java/main/Main.java, src/main/java/main/MainUI.form, src/main/java/main/MainUI.java, src/main/java/main/ProgressGui.java, src/main/java/main/VisualizationsGui.java
Tasks from Sprint Plan #7:
-The input/script GUI should be coupled to the visualization GUI
=> Gui Coupling

src/main/java/enums/ComputeOperator.java, src/main/java/operations/ComputeOperation.java, src/main/java/operations/compute/AvgComputation.java, src/main/java/operations/compute/Computation.java, src/main/java/operations/compute/ComputationFactory.java, src/main/java/operations/compute/CountComputation.java, src/main/java/operations/compute/MaxComputation.java, src/main/java/operations/compute/MinComputation.java, src/main/java/operations/compute/StdevComputation.java, src/main/java/operations/compute/SumComputation.java, src/test/java/operations/ComputeOperationTest.java, src/test/java/operations/compute/ComputationFactoryTest.java, src/test/java/operations/compute/ComputationTest.java
Operation for doing computations on tables (and so also on chunks). Together with the ForEachChunkOperation computations on chunks are possible.
=> Compute operation

checkstyle.xml, common/.checkstyle, common/checkstyle.xml, computation/.checkstyle, computation/checkstyle.xml, data/.checkstyle, data/checkstyle.xml, export/.checkstyle, export/checkstyle.xml, gui/.checkstyle, gui/checkstyle.xml, input/.checkstyle, input/checkstyle.xml, script/.checkstyle
Checkstyle is back! To activate:
For each project:
1. Refresh project
2. Project -> Properties -> Checkstyle -> Check "Checkstyle active for this project"
Added checkstyle for each module except script.
=> The Return of the Checkstyle

computation/src/main/java/net/tudelft/hi/e/computation/BetweenOperation.java, computation/src/main/java/net/tudelft/hi/e/computation/DayGrouper.java, computation/src/main/java/net/tudelft/hi/e/computation/LsaOperation.java, computation/src/main/java/net/tudelft/hi/e/computation/SingleGrouper.java, computation/src/test/java/net/tudelft/hi/e/computation/BetweenOperationTest.java, computation/src/test/java/net/tudelft/hi/e/computation/ConstraintOperationTest.java, computation/src/test/java/net/tudelft/hi/e/computation/LsaOperationTest.java, computation/src/test/java/net/tudelft/hi/e/computation/SingleOccurrenceValuePatternTest.java
Tested, and fixed some equal and hash methods
=> LsaOperation and BetweenOperation tests

computation/src/main/java/net/tudelft/hi/e/computation/ForEachChunkOperation.java
The ForEachChunkOperation now has all chunks combined as result elementdata.
=> Each chunk fix

.idea/sonarSettings.xml, script/src/main/java/net/tudelft/hi/e/script/OperationFactory.java, script/src/main/java/net/tudelft/hi/e/script/ScriptErrorListener.java, script/src/main/java/net/tudelft/hi/e/script/ScriptExecutionManager.java, script/src/main/java/net/tudelft/hi/e/script/ScriptVisitor.java
=> Script branch patch

script/src/main/antlr4/net/tudelft/hi/e/script/AnalysisLang.g4, script/src/test/java/net/tudelft/hi/e/script/ScriptExecutionManagerTest.java, script/src/test/resources/script_commented.txt
The lines starting with a # are skipped.
=> The script now supports comments.

common/src/main/java/net/tudelft/hi/e/common/exceptions/ExportException.java, export/src/main/java/net/tudelft/hi/e/export/Exporter.java, export/src/main/java/net/tudelft/hi/e/export/SettingsBuilder.java, export/src/main/java/net/tudelft/hi/e/export/SettingsWriter.java, gui/src/main/java/net/tudelft/hi/e/gui/ProgressGui.java
SonarQube fixes, 0 issues left.
=> Export branch patch
